config/routes.rb
Timetracker::Application.routes.draw do
  resource  :session

  namespace :admin do
    resources  :companies
  end

  resources :users do
    collection do
      get 'activity'
    end
  end

  resources :jobs do
    collection do
      get 'activity'
    end
  end

  resources :labors do
    member do
      get  'toggle_end'
      post 'finish'
    end
    collection do
      get  'week'
      get  'month'
      get  'period'
      post 'show_stories'
    end
  end
  match 'about' => "home#about"
  root :to => "labors#index"
  match 'login'  => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signup' => 'users#new', :as => :signup
  match 'activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

end

app/models/company.rb
class Company < ActiveRecord::Base

  has_many :users
  has_many :jobs

  validates_presence_of :name

  validates_uniqueness_of :name

end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::AdminController

  before_filter :find_company, :except => :index

  def index
    redirect_to :show
  end

  def update
    if @company.update_attributes(params[:company])
      redirect_to(admin_company_path(@company), :notice => t('companies.edit.successfully'))
    else
      render :action => 'edit'
    end
  end

  protected

  def find_company
    @company = current_user.company
  end

end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/views/admin/companies/edit.html.haml
%h1
  = "#{t('companies.edit.edit_company')} #{@company.name}"

= form_for [:admin, @company] do |c|
  = error_messages_for :company
  %p
    = c.label :name
    %br/
    = c.text_field :name
  %p
    = c.label :address
    %br/
    = c.text_field :address
  %p
    = c.submit t('companies.edit.save_company')

app/views/admin/companies/show.html.haml
%h1
  = @company.name

%p
  = link_to("Modificar", edit_admin_company_path(@company))