config/routes.rb
Timetracker::Application.routes.draw do
  resource  :session

  namespace :admin do
    resources  :companies
  end

  resources :users do
    collection do
      get 'activity'
    end
  end

  resources :jobs do
    collection do
      get 'activity'
    end
  end

  resources :labors do
    member do
      get  'toggle_end'
      post 'finish'
    end
    collection do
      get  'week'
      get  'month'
      get  'period'
      post 'show_stories'
    end
  end
  match 'about' => "home#about"
  root :to => "labors#index"
  match 'login'  => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signup' => 'users#new', :as => :signup
  match 'activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

end

app/views/shared/_menu.html.haml
%header{:id => "banner", :class => "body"}
  %p
    =link_to(current_user.present? ? current_user.company.commercial_name : "TimeTracker", root_path)
  %nav
    %ul
      %li{:class => "active"}
        =link_to("Proyectos", jobs_path)
      %li Contactar
      %li Contactar
      %li Contactar
      - if current_user.present? and current_user.is_admin?
        %li
          =link_to("Mi empresa", admin_company_path(current_user.company))

app/views/shared/_sidebar.html.haml
.about-me
  %h3 About Me
  %p
    %a{:href => "index.html"}
      %img.float-left{:alt => "firefox", :height => "40", :src => "/images/gravatar.jpg", :width => "40"}/
    Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum.
    Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu
    posuere nunc justo tempus leo
    %a{:href => "index.html"} Learn more...
.sidemenu
  %h3 Sidebar Menu
  %ul
    %li
      %a{:href => "index.html"} Home
    %li
      %a{:href => "index.html#TemplateInfo"} TemplateInfo
    %li
      %a{:href => "style.html"} Style Demo
    %li
      %a{:href => "blog.html"} Blog
    %li
      %a{:href => "archives.html"} Archives
    %li
      %a{:href => "http://www.dreamtemplate.com", :title => "Web Templates"} Web Templates
.sidemenu
  %h3 Sponsors
  %ul
    %li
      %a{:href => "http://www.dreamtemplate.com", :title => "Website Templates"}
        DreamTemplate
        %br/
        %span Over 6,000+ Premium Web Templates
    %li
      %a{:href => "http://www.themelayouts.com", :title => "WordPress Themes"}
        ThemeLayouts
        %br/
        %span Premium WordPress &amp; Joomla Themes
    %li
      %a{:href => "http://www.imhosted.com", :title => "Website Hosting"}
        ImHosted.com
        %br/
        %span Affordable Web Hosting Provider
    %li
      %a{:href => "http://www.dreamstock.com", :title => "Stock Photos"}
        DreamStock
        %br/
        %span Download Amazing Stock Photos
    %li
      %a{:href => "http://www.evrsoft.com", :title => "Website Builder"}
        Evrsoft
        %br/
        %span Website Builder Software &amp; Tools
    %li
      %a{:href => "http://www.webhostingwp.com", :title => "Web Hosting"}
        Web Hosting
        %br/
        %span Top 10 Hosting Reviews
.popular
  %h3 Most Popular
  %ul
    %li
      %a{:href => "index.html"} Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
      %br/
      %span Posted on December 22, 2010
    %li
      %a{:href => "index.html"} Cras fringilla magna. Phasellus suscipit.
      %br/
      %span Posted on December 20, 2010
    %li
      %a{:href => "index.html"} Morbi tincidunt, orci ac convallis aliquam.
      %br/
      %span Posted on December 15, 2010
    %li
      %a{:href => "index.html"} Ipsum dolor sit amet, consectetuer adipiscing elit.
      %br/
      %span Posted on December 14, 2010
    %li
      %a{:href => "index.html"} Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem
      %br/
      %span Posted on December 12, 2010
/ /sidebar
/ content
/ /content-out