config/routes.rb
Timetracker::Application.routes.draw do
  resource  :session

  namespace :admin do
    resources  :companies
  end

  resources :users do
    collection do
      get 'activity'
    end
  end

  resources :jobs do
    collection do
      get 'activity'
    end
  end

  resources :labors do
    member do
      get  'toggle_end'
      post 'finish'
    end
    collection do
      get  'week'
      get  'month'
      get  'period'
      post 'show_stories'
    end
  end
  match 'about' => "home#about"
  root :to => "labors#index"
  match 'login'  => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signup' => 'users#new', :as => :signup
  match 'activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

end

app/models/labor.rb
class Labor < ActiveRecord::Base

  belongs_to :user
  belongs_to :job

  validates_presence_of :user_id, :job_id

  named_scope :actives, :conditions => "start_at is not null", :order => "labors.created_at desc"

  before_save :update_time

  def self.sum_hours(date)
    tot_hours = tot_frac = sum_hours = frac = 0
    where(["created_at between ? and ?", date.beginning_of_day.utc, date.end_of_day.utc]).order("labors.created_at desc").each do |labor|
      if labor.start_at.present?
        sum_hours, frac = labor.calculate_difference
        frac            = Labor.decimal_to_time(frac)
      end
      sum_hours = sum_hours.to_i + labor.hours
      frac      = frac.to_i + labor.minutes
    end
    tot_hours = sum_hours.to_i
    tot_frac  = frac.to_i

    sum_hours, frac = tot_frac.divmod(60)
    tot_hours      += sum_hours.to_i
    minutes         = frac.to_i
    return "#{tot_hours}:#{minutes}"
  end

  def self.today_activity(date)
    where(["created_at between ? and ?", date.beginning_of_day.utc, date.end_of_day.utc]).order("labors.created_at desc")
  end

  def calculate_difference
    #devuelve los minutos en base 100  1 hora = 100 minutos
    difference  = Time.now - start_at
    hours_total =  difference / (60 * 60)
    return ("%2.2f" % hours_total).split('.')
  end

  def has_story?
    sid.to_i > 0
  end

  def saved_hours
    "#{hours}:#{minutes}"
  end

  def set_time_value(time)
    aux_hours, aux_minutes = time.split(":")
    self.hours             = aux_hours.to_i
    self.minutes           = aux_minutes.to_i if (aux_minutes.to_i < 60)
  end
  
  def update_time
    if end_at.present?
      tot_hours, frac      = calculate_difference
      frac                 = Labor.decimal_to_time(frac)
      sum_hours, sum_frac  = frac.to_i.divmod(100)
      tot_hours            = tot_hours.to_i + sum_hours.to_i
      tot_minutes          = sum_frac.to_i
      self.hours          += tot_hours.to_i
      tot_frac             = sum_frac.to_i + self.minutes
      sum_hours, frac      = tot_frac.divmod(60)
      self.hours          += sum_hours.to_i
      self.minutes         = frac.to_i
      self.start_at        = nil
      self.end_at          = nil
      save
    end
  end

  protected

  def self.decimal_to_time(decimal)
    #convertimos el tiempo en base 100 a base 60 con una sencilla regla de tres
    ((60 * decimal.to_i) / 100).round
  end
end

app/controllers/labors_controller.rb
class LaborsController < MemberController
  before_filter :set_index_values, :only => :index

  def create
    if set_labor_values
      only_one_labor_active(@labor)
      flash[:notice] = ('Actividad creada correctamente')
      redirect_to(labors_path)
    else
      set_index_values
      render :action => :index
    end
  end

  def destroy
    if @labor.destroy
      notice_stickie('Actividad borrada correctamente')
    end
    redirect_to(labors_path)
  end

  def finish
    toggle_story
    if @labor.save
      update_pivotal('finished') if @use_pt
      notice_stickie('Actividad actualizada')
    end
    redirect_to labors_path
  end

  def index
    if @labor.start_at.present?
      notice_stickie('No se puede modificar una actividad que está en marcha. <br />Detén primero la actividad y luego podrás
 modificarla.')
      @labor = Labor.new
    end
  end

  def month
    #@start_at = Date.today.beginning_of_month
    #@end_at   = Date.today.end_of_month
  end

  def show_stories
    @stories = @project.stories.all(:state => "unstarted")
    render :layout => false
  end

  def toggle_end
    toggle_story
    if @labor.save
      only_one_labor_active(@labor)
      notice_stickie('Actividad actualizada')
    end
    redirect_to labors_path
  end

  def update
    @labor.attributes   = params[:labor]
    @labor.job          = find_a_job(params[:job].to_s)
    @labor.set_time_value(params[:time])
    if @labor.save
      notice_stickie('Actividad actualizada correctamente')
    end

    redirect_to labors_path
  end

  def week
    find_week_hours
  end

  protected

  def find_a_job(job_name)
    current_user.company.jobs.find_or_create_by_title(job_name)
  end

  def find_labor
    @labor = current_user.labors.find(params[:id])
  end

  def find_story(sid)
    @story = @project.stories.find(sid)
  end

  def find_week_hours
    d         = params[:date] || Date.today
    @start_at = Date.commercial(d.cwyear, d.cweek, 1)
    @end_at   = Date.commercial(d.cwyear, d.cweek, 6)
    @week     = Hash.new
    i = 0
    (@start_at..@end_at).each do |date|
      @week[i] = [date, current_user.labors.sum_hours(date)]
      i += 1
    end
  end

  def only_one_labor_active(labor)
    if labor.start_at.present?
      current_user.labors.find(:all, :conditions => ["(start_at is not null and id<>?)", labor.id]).each do |labor|
        labor.end_at = Time.now
        labor.update_time
      end
    end
  end

  def set_date
    params[:date].present? ? Date.parse(params[:date]) : Time.now
  rescue ArgumentError
    Time.now
  end

  def set_index_values
    find_labor if params[:id]
    @labor     ||= Labor.new
    @date      = set_date
    @recents   = current_user.labors.today_activity(@date)
    @total     = current_user.labors.sum_hours(@date)
  end

  def set_labor_values
    @labor = current_user.labors.new(params[:labor])
    find_story(params[:sid].to_i) if (params[:sid] and (params[:sid].to_i > 0) and @use_pt)

    if @use_pt and @story
      @labor.content       = @story.name
      @labor.job           = find_a_job(@project.name.to_s)
      @labor.sid           = @story.id
    else
      @labor.job           = find_a_job(params[:job].to_s)
    end

    if params[:time]
      @labor.set_time_value(params[:time])
    else
      @labor.start_at        = Time.now
    end

    if @labor.save
      @labor.update_attribute(:created_at, set_date)
      if @use_pt and @story
        @story.current_state = 'started'
        @story.update
      end

      return true
    else
      return false
    end
  end
end

app/helpers/labors_helper.rb
module LaborsHelper
end

app/views/labors/_recent.html.haml
.post
  .right
    %h2
      =h("#{recent.job.title} - #{recent.content}")
    %p.post_content
      El perro de san roque
    .post-meta
      %ul
        %li.time
          =link_to((recent.start_at.present? ? "Detener" : "Reanudar"), toggle_end_labor_path(recent))
        %li.user
          =button_to("Finalizar", finish_labor_path(recent)) if recent.has_story?
        %li.comment
          =link_to_if((!recent.start_at.present?), "Modificar", labors_path(:id => recent.id))
        %li.permalink
          =link_to("Borrar", labor_path(recent), :method => :delete, :confirm => "Estás seguro?")
  .left
    %p.dateinfo
      = recent.created_at.strftime('%b')
      = recent.created_at.strftime('%d')
      %span
        ="#{recent.hours}:#{recent.minutes}"

app/views/labors/index.html.haml
%h1= "#{@date.strftime('%A, %d %b %Y')} #{t('labors.index.total_hours', :total => @total)}"
= error_messages_for :labor
-form_for(@labor) do |f|
  =hidden_field_tag :date, params[:date]
  =label_tag :job, t('labors.index.job')
  =text_field_tag :job, (@labor.job.title if @labor.job.present?)
  =label_tag :time, t('labors.index.time')
  =text_field_tag :time, @labor.saved_hours, :size => 10
  %br/
  =f.label :content, Labor.human_attribute_name(:content)
  =f.text_field :content, :size => 80
  =f.submit((@labor.id.present? ? t('labors.index.save_changes') : t('labors.index.start')), :class => "button")
= set_focus_to_id('#job')
=render :partial => 'recent', :collection => @recents
-content_for :sidebar do
  .popular
    %h3 Historias
    - if @project.present?
      =link_to_remote("Ver historias pendientes", :url => show_stories_labors_path, :update => "pt_stories")
      #pt_stories